import Head from "next/head";
import Image from "next/image";
import Navbar from "../Components/Navbar";
import Hero from "../Components/Hero";
import WhyChoose from "../Components/WhyChoose";
import Articles from "../Components/Articles";
import Footer from "../Components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>EasyBank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <Hero />
        <WhyChoose />
        <Articles />
        <Footer />
      </main>
    </>
  );
}
